### ISSUE TITLE
Travis builds failing for unknown reason

### ISSUE THREAD

**Issue by JelleAalbers** [JelleAalbers/blueice#14]
Currently our travis builds are failing with the very unhelpful "core dumped" message. I first thought it was related to iminuit, but removing all iminuit installation instructions hasn't helped. I hope this is a temporary problem on the travis CI side, otherwise we may have to use stuff like https://github.com/springmeyer/travis-coredump to diagnose it.

**Comment by pelssers** [comment]
I tried to narrow down the problem but it does not seem to be related to any of the usual suspects (iminuit or matplotlib). I also cannot reproduce it locally.

**Comment by pelssers** [comment]
I just restarted the last travis build that worked to see if any of the python packages was updated and the cause of the problem. The build finished fine.
The build also installed iminuit which is currently disabled in the master .travis.yml so this we can safely enable again I think.

**Comment by JelleAalbers** [comment]
I agree, clearly it isn't iminuit's fault, since we get the same problem with the scipy minimizers. Matplotlib was another good guess... this is strange indeed.

**Comment by kdund** [comment]
Does travis run pytest? I remember that the default pytest with miniconda failed to run some of the tests.

**Comment by JelleAalbers** [comment]
It's matplotlib: https://travis-ci.org/JelleAalbers/blueice/builds/164738827. I had to release a new multihist version since that too "depended" on matplotlib... 

@kdund yes, Travis runs pytest; these problems were with pytest 2 (I used a pytest 3 feature somewhere). I've now explicitely required pytest3 in the installation so that should not come up again.

**Comment by JelleAalbers** [comment]
Green badge again :-)
