### ISSUE TITLE
Allow negative rate multipliers

### ISSUE THREAD

**Issue by kdund** [JelleAalbers/blueice#16]
It might be desirable to subtract two pdfs. (say, to avoid double-counting of a contaminant of a calibration source)

Proposed implementation: 
    -with a suitable flag, allow a source rate_multiplier to be negative
    -if such a flag is set, truncate the summed pdf to be above 0.

**Comment by kdund** [comment]
The branch sourcesubstraction now contains a proposed solution. If a source has the property "allowed_negative" set to True, checks for negative rates are bypassed.

 Note that in the current implementation, one relies on outlier_likelihood to be set, so that extended_loglikelihood truncates probabilities below zero. This seems slightly messy to me, I'll keep thinking about the alternatives.

**Comment by JelleAalbers** [comment]
I think this has been merged, right?

**Comment by kdund** [comment]
yes

**Comment by kdund** [comment]
âs such, close.
